### ISSUE TITLE
Checklist for Pirog

### ISSUE THREAD

**Issue by pirog** [pirog/website#1]
- [ ] Get Travis rolling with init script from john
- [ ] Get DB pull script from John
- [ ] Get Travis lint/cs/unit tests and database pull 
- [ ] Setup manually things like issue templates/bots/code climate
- [ ] Setup git branch protection
- [ ] Update README with instructions on how to get rolling

**Comment by dustinleblanc** [comment]
just happened to be stopping by this repo, not sure we want a db pull script, given this is a laravel project, it'd probably be better for us to have robust db seeders instead. Laravel makes this fairly easy to setup with factories and seeders: https://laravel.com/docs/5.8/seeding

**Comment by pirog** [comment]
better in what way? 

i think our goal here is to have a lowest common denominator and portable asset we can use on all our projects to populate a database, a script that pulls from platform seems like it would fit the bill and would not be coupled to the implementation specifics of a given project.

certainly can still use seeding to accomplish other goals but im not sure its a drop in replacement for what the pull script aims to accomplish
